
(global-set-key [f2]   'indent-buffer)
(global-set-key [f3]   'my-file-make-writeable)
(global-set-key [f4]   'goto-line)
(global-set-key [f5]   'quick-calc)
(global-set-key [f6]   'revert-buffer)
(global-set-key [f7]   'my-file-reopen-as-root)

(global-set-key (kbd "H-\"") 'delete-other-windows)
(global-set-key (kbd "H-<") 'split-window-below)
(global-set-key (kbd "H->") 'split-window-right)
(global-set-key (kbd "H-f") 'ido-find-file)
(global-set-key (kbd "H-s") 'save-buffer)
(global-set-key (kbd "H-b") 'ido-switch-buffer)
(global-set-key (kbd "H-B") 'semantic-mrub-switch-tags)
(global-set-key (kbd "H-o") 'other-window)
(global-set-key (kbd "H-SPC") 'set-mark-command)
(global-set-key (kbd "H-a") 'set-mark-command)
(global-set-key (kbd "H-u") 'kill-region)
(global-set-key (kbd "H-i") 'kill-ring-save)
(global-set-key (kbd "H-y") 'yank)
(global-set-key (kbd "H-e") 'yank)
(global-set-key (kbd "M-e") 'yank-pop)
(global-set-key (kbd "H-u") 'kill-region)
(global-set-key (kbd "H-k") 'ido-kill-buffer)
(global-set-key (kbd "H-é") 'rgrep)
(global-set-key (kbd "s-d") 'previous-line)
(global-set-key (kbd "s-s") 'next-line)
(global-set-key (kbd "s-r") 'right-char)
(global-set-key (kbd "s-t") 'left-char)
(global-set-key (kbd "ð") 'previous-line)
(global-set-key (kbd "ß") 'next-line)
(global-set-key (kbd "þ") 'left-char)
(global-set-key (kbd "®") 'right-char)
(global-set-key (kbd "C-ð") 'backward-paragraph)
(global-set-key (kbd "C-ß") 'forward-paragraph)
(global-set-key (kbd "C-®") 'right-word)
(global-set-key (kbd "C-þ") 'left-word)

(global-set-key (kbd "M-g") 'keyboard-quit)
(global-set-key (kbd "H-g") 'keyboard-quit)
(global-set-key (kbd "s-g") 'keyboard-quit)

(global-set-key (kbd "C-©") 'comment-or-uncomment-region)

(fset 'comment-or-uncomment-paragraph
   (lambda (&optional arg) "Keyboard macro." (interactive "p") (kmacro-exec-ring-item (quote ([134217832 67109033 134217853] 0 "%d")) arg)))
(global-set-key (kbd "©") 'comment-or-uncomment-paragraph)
