;;; Color theme based on Tango Palette. Created by danranx@gmail.com


(defun color-theme-tango ()
  "A color theme based on Tango Palette."
  (interactive)
  (color-theme-install
   '(color-theme-tango
     ((background-color . "#000000")
      (background-mode . dark)
      (border-color . "#888a85")
      (cursor-color . "#d3d7cf")
      (foreground-color . "#ebe0ce")
      (mouse-color . "#8ae234"))
     ((help-highlight-face . underline)
      (ibuffer-dired-buffer-face . font-lock-function-name-face)
      (ibuffer-help-buffer-face . font-lock-comment-face)
      (ibuffer-hidden-buffer-face . font-lock-warning-face)
      (ibuffer-occur-match-face . font-lock-warning-face)
      (ibuffer-read-only-buffer-face . font-lock-type-face)
      (ibuffer-special-buffer-face . font-lock-keyword-face)
      (ibuffer-title-face . font-lock-type-face))
     (border ((t (:background "#888a85"))))
     (fringe ((t (:background "grey10"))))
     (mode-line ((t (:foreground "#ebe0ce" :background "#4c4039"))))
     (region ((t (:background "#181818"))))
     (font-lock-builtin-face ((t (:foreground "#ef2929"))))
     (font-lock-comment-face ((t (:foreground "#cc0000"))))
     (font-lock-constant-face ((t (:foreground "#729fcf"))))
     (font-lock-doc-face ((t (:foreground "#ad7fa8"))))
     (font-lock-keyword-face ((t (:foreground "#ad7fa8"))))
     (font-lock-string-face ((t (:foreground "#c17d11"))))
     (font-lock-type-face ((t (:foreground "#8ae234" :bold t))))
     (font-lock-variable-name-face ((t (:foreground "#eeeeec"))))
     (font-lock-warning-face ((t (:bold t :foreground "#f57900"))))
     (font-lock-function-name-face ((t (:foreground "#3464a4" :bold t))))
     (comint-highlight-input ((t (:italic t :bold t))))
     (comint-highlight-prompt ((t (:foreground "#729fcf" :bold t))))
     (isearch ((t (:background "#f57900" :foreground "#2e3436"))))
     (isearch-lazy-highlight-face ((t (:foreground "#2e3436" :background "#e9b96e"))))
     (show-paren-match-face ((t (:foreground "#2e3436" :background "#73d216"))))
     (show-paren-mismatch-face ((t (:background "#ad7fa8" :foreground "#2e3436"))))
     (minibuffer-prompt ((t (:foreground "#729fcf"))))
     (info-xref ((t (:foreground "#729fcf"))))
     (info-xref-visited ((t (:foreground "#ad7fa8"))))
     (mmm-default-submode-face ((t (:background "#000000"))))
     )))
(provide 'color-theme-tango)
